/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ElektrokolaRouteImport } from './routes/elektrokola'
import { Route as KolaRouteImport } from './routes/kola'
import { Route as KoloSlugRouteImport } from './routes/kolo.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ElektrokolaRoute = ElektrokolaRouteImport.update({
  id: '/elektrokola',
  path: '/elektrokola',
  getParentRoute: () => rootRouteImport,
} as any)
const KolaRoute = KolaRouteImport.update({
  id: '/kola',
  path: '/kola',
  getParentRoute: () => rootRouteImport,
} as any)
const KoloSlugRoute = KoloSlugRouteImport.update({
  id: '/kolo/$slug',
  path: '/kolo/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/elektrokola': typeof ElektrokolaRoute
  '/kola': typeof KolaRoute
  '/kolo/$slug': typeof KoloSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/elektrokola': typeof ElektrokolaRoute
  '/kola': typeof KolaRoute
  '/kolo/$slug': typeof KoloSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/elektrokola': typeof ElektrokolaRoute
  '/kola': typeof KolaRoute
  '/kolo/$slug': typeof KoloSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/elektrokola' | '/kola' | '/kolo/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/elektrokola' | '/kola' | '/kolo/$slug'
  id: '__root__' | '/' | '/elektrokola' | '/kola' | '/kolo/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ElektrokolaRoute: typeof ElektrokolaRoute
  KolaRoute: typeof KolaRoute
  KoloSlugRoute: typeof KoloSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/elektrokola': {
      id: '/elektrokola'
      path: '/elektrokola'
      fullPath: '/elektrokola'
      preLoaderRoute: typeof ElektrokolaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kola': {
      id: '/kola'
      path: '/kola'
      fullPath: '/kola'
      preLoaderRoute: typeof KolaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kolo/$slug': {
      id: '/kolo/$slug'
      path: '/kolo/$slug'
      fullPath: '/kolo/$slug'
      preLoaderRoute: typeof KoloSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ElektrokolaRoute: ElektrokolaRoute,
  KolaRoute: KolaRoute,
  KoloSlugRoute: KoloSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
