/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BazarRouteImport } from './routes/bazar'
import { Route as ElektrokolaRouteImport } from './routes/elektrokola'
import { Route as KolaRouteImport } from './routes/kola'
import { Route as KontaktRouteImport } from './routes/kontakt'
import { Route as KosikRouteImport } from './routes/kosik'
import { Route as OMneRouteImport } from './routes/o-mne'
import { Route as ServisRouteImport } from './routes/servis'
import { Route as ElektrokolaIndexRouteImport } from './routes/elektrokola.index'
import { Route as ElektrokolaZnackaRouteImport } from './routes/elektrokola.$znacka'
import { Route as KolaIndexRouteImport } from './routes/kola.index'
import { Route as KolaZnackaRouteImport } from './routes/kola.$znacka'
import { Route as KoloSlugRouteImport } from './routes/kolo.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BazarRoute = BazarRouteImport.update({
  id: '/bazar',
  path: '/bazar',
  getParentRoute: () => rootRouteImport,
} as any)
const ElektrokolaRoute = ElektrokolaRouteImport.update({
  id: '/elektrokola',
  path: '/elektrokola',
  getParentRoute: () => rootRouteImport,
} as any)
const KolaRoute = KolaRouteImport.update({
  id: '/kola',
  path: '/kola',
  getParentRoute: () => rootRouteImport,
} as any)
const KontaktRoute = KontaktRouteImport.update({
  id: '/kontakt',
  path: '/kontakt',
  getParentRoute: () => rootRouteImport,
} as any)
const KosikRoute = KosikRouteImport.update({
  id: '/kosik',
  path: '/kosik',
  getParentRoute: () => rootRouteImport,
} as any)
const OMneRoute = OMneRouteImport.update({
  id: '/o-mne',
  path: '/o-mne',
  getParentRoute: () => rootRouteImport,
} as any)
const ServisRoute = ServisRouteImport.update({
  id: '/servis',
  path: '/servis',
  getParentRoute: () => rootRouteImport,
} as any)
const ElektrokolaIndexRoute = ElektrokolaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ElektrokolaRoute,
} as any)
const ElektrokolaZnackaRoute = ElektrokolaZnackaRouteImport.update({
  id: '/$znacka',
  path: '/$znacka',
  getParentRoute: () => ElektrokolaRoute,
} as any)
const KolaIndexRoute = KolaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => KolaRoute,
} as any)
const KolaZnackaRoute = KolaZnackaRouteImport.update({
  id: '/$znacka',
  path: '/$znacka',
  getParentRoute: () => KolaRoute,
} as any)
const KoloSlugRoute = KoloSlugRouteImport.update({
  id: '/kolo/$slug',
  path: '/kolo/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bazar': typeof BazarRoute
  '/elektrokola': typeof ElektrokolaRouteWithChildren
  '/kola': typeof KolaRouteWithChildren
  '/kontakt': typeof KontaktRoute
  '/kosik': typeof KosikRoute
  '/o-mne': typeof OMneRoute
  '/servis': typeof ServisRoute
  '/elektrokola/$znacka': typeof ElektrokolaZnackaRoute
  '/kola/$znacka': typeof KolaZnackaRoute
  '/kolo/$slug': typeof KoloSlugRoute
  '/elektrokola/': typeof ElektrokolaIndexRoute
  '/kola/': typeof KolaIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bazar': typeof BazarRoute
  '/kontakt': typeof KontaktRoute
  '/kosik': typeof KosikRoute
  '/o-mne': typeof OMneRoute
  '/servis': typeof ServisRoute
  '/elektrokola/$znacka': typeof ElektrokolaZnackaRoute
  '/kola/$znacka': typeof KolaZnackaRoute
  '/kolo/$slug': typeof KoloSlugRoute
  '/elektrokola': typeof ElektrokolaIndexRoute
  '/kola': typeof KolaIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bazar': typeof BazarRoute
  '/elektrokola': typeof ElektrokolaRouteWithChildren
  '/kola': typeof KolaRouteWithChildren
  '/kontakt': typeof KontaktRoute
  '/kosik': typeof KosikRoute
  '/o-mne': typeof OMneRoute
  '/servis': typeof ServisRoute
  '/elektrokola/$znacka': typeof ElektrokolaZnackaRoute
  '/kola/$znacka': typeof KolaZnackaRoute
  '/kolo/$slug': typeof KoloSlugRoute
  '/elektrokola/': typeof ElektrokolaIndexRoute
  '/kola/': typeof KolaIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bazar'
    | '/elektrokola'
    | '/kola'
    | '/kontakt'
    | '/kosik'
    | '/o-mne'
    | '/servis'
    | '/elektrokola/$znacka'
    | '/kola/$znacka'
    | '/kolo/$slug'
    | '/elektrokola/'
    | '/kola/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bazar'
    | '/kontakt'
    | '/kosik'
    | '/o-mne'
    | '/servis'
    | '/elektrokola/$znacka'
    | '/kola/$znacka'
    | '/kolo/$slug'
    | '/elektrokola'
    | '/kola'
  id:
    | '__root__'
    | '/'
    | '/bazar'
    | '/elektrokola'
    | '/kola'
    | '/kontakt'
    | '/kosik'
    | '/o-mne'
    | '/servis'
    | '/elektrokola/$znacka'
    | '/kola/$znacka'
    | '/kolo/$slug'
    | '/elektrokola/'
    | '/kola/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BazarRoute: typeof BazarRoute
  ElektrokolaRoute: typeof ElektrokolaRouteWithChildren
  KolaRoute: typeof KolaRouteWithChildren
  KontaktRoute: typeof KontaktRoute
  KosikRoute: typeof KosikRoute
  OMneRoute: typeof OMneRoute
  ServisRoute: typeof ServisRoute
  KoloSlugRoute: typeof KoloSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bazar': {
      id: '/bazar'
      path: '/bazar'
      fullPath: '/bazar'
      preLoaderRoute: typeof BazarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/elektrokola': {
      id: '/elektrokola'
      path: '/elektrokola'
      fullPath: '/elektrokola'
      preLoaderRoute: typeof ElektrokolaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kola': {
      id: '/kola'
      path: '/kola'
      fullPath: '/kola'
      preLoaderRoute: typeof KolaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontakt': {
      id: '/kontakt'
      path: '/kontakt'
      fullPath: '/kontakt'
      preLoaderRoute: typeof KontaktRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kosik': {
      id: '/kosik'
      path: '/kosik'
      fullPath: '/kosik'
      preLoaderRoute: typeof KosikRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/o-mne': {
      id: '/o-mne'
      path: '/o-mne'
      fullPath: '/o-mne'
      preLoaderRoute: typeof OMneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servis': {
      id: '/servis'
      path: '/servis'
      fullPath: '/servis'
      preLoaderRoute: typeof ServisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/elektrokola/': {
      id: '/elektrokola/'
      path: '/'
      fullPath: '/elektrokola/'
      preLoaderRoute: typeof ElektrokolaIndexRouteImport
      parentRoute: typeof ElektrokolaRoute
    }
    '/elektrokola/$znacka': {
      id: '/elektrokola/$znacka'
      path: '/$znacka'
      fullPath: '/elektrokola/$znacka'
      preLoaderRoute: typeof ElektrokolaZnackaRouteImport
      parentRoute: typeof ElektrokolaRoute
    }
    '/kola/': {
      id: '/kola/'
      path: '/'
      fullPath: '/kola/'
      preLoaderRoute: typeof KolaIndexRouteImport
      parentRoute: typeof KolaRoute
    }
    '/kola/$znacka': {
      id: '/kola/$znacka'
      path: '/$znacka'
      fullPath: '/kola/$znacka'
      preLoaderRoute: typeof KolaZnackaRouteImport
      parentRoute: typeof KolaRoute
    }
    '/kolo/$slug': {
      id: '/kolo/$slug'
      path: '/kolo/$slug'
      fullPath: '/kolo/$slug'
      preLoaderRoute: typeof KoloSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ElektrokolaRouteChildren {
  ElektrokolaZnackaRoute: typeof ElektrokolaZnackaRoute
  ElektrokolaIndexRoute: typeof ElektrokolaIndexRoute
}

const ElektrokolaRouteChildren: ElektrokolaRouteChildren = {
  ElektrokolaZnackaRoute: ElektrokolaZnackaRoute,
  ElektrokolaIndexRoute: ElektrokolaIndexRoute,
}

const ElektrokolaRouteWithChildren = ElektrokolaRoute._addFileChildren(
  ElektrokolaRouteChildren,
)

interface KolaRouteChildren {
  KolaZnackaRoute: typeof KolaZnackaRoute
  KolaIndexRoute: typeof KolaIndexRoute
}

const KolaRouteChildren: KolaRouteChildren = {
  KolaZnackaRoute: KolaZnackaRoute,
  KolaIndexRoute: KolaIndexRoute,
}

const KolaRouteWithChildren = KolaRoute._addFileChildren(KolaRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BazarRoute: BazarRoute,
  ElektrokolaRoute: ElektrokolaRouteWithChildren,
  KolaRoute: KolaRouteWithChildren,
  KontaktRoute: KontaktRoute,
  KosikRoute: KosikRoute,
  OMneRoute: OMneRoute,
  ServisRoute: ServisRoute,
  KoloSlugRoute: KoloSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
