/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BazarRouteImport } from './routes/bazar'
import { Route as ElektrokolaRouteImport } from './routes/elektrokola'
import { Route as KolaRouteImport } from './routes/kola'
import { Route as KontaktRouteImport } from './routes/kontakt'
import { Route as KosikRouteImport } from './routes/kosik'
import { Route as OMneRouteImport } from './routes/o-mne'
import { Route as ObchodniPodminkyRouteImport } from './routes/obchodni-podminky'
import { Route as OchranaOsobnichUdajuRouteImport } from './routes/ochrana-osobnich-udaju'
import { Route as OdstoupeniOdSmlouvyRouteImport } from './routes/odstoupeni-od-smlouvy'
import { Route as ServisRouteImport } from './routes/servis'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as ElektrokolaIndexRouteImport } from './routes/elektrokola.index'
import { Route as ElektrokolaZnackaRouteImport } from './routes/elektrokola.$znacka'
import { Route as KolaIndexRouteImport } from './routes/kola.index'
import { Route as KolaZnackaRouteImport } from './routes/kola.$znacka'
import { Route as KoloSlugRouteImport } from './routes/kolo.$slug'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminKategorieRouteImport } from './routes/_authenticated/admin.kategorie'
import { Route as AuthenticatedAdminNastaveniRouteImport } from './routes/_authenticated/admin.nastaveni'
import { Route as AuthenticatedAdminObjednavkyRouteImport } from './routes/_authenticated/admin.objednavky'
import { Route as AuthenticatedAdminProduktyRouteImport } from './routes/_authenticated/admin.produkty'
import { Route as AuthenticatedAdminServisRouteImport } from './routes/_authenticated/admin.servis'
import { Route as AuthenticatedAdminSpravciRouteImport } from './routes/_authenticated/admin.spravci'
import { Route as AuthenticatedAdminZpravyRouteImport } from './routes/_authenticated/admin.zpravy'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BazarRoute = BazarRouteImport.update({
  id: '/bazar',
  path: '/bazar',
  getParentRoute: () => rootRouteImport,
} as any)
const ElektrokolaRoute = ElektrokolaRouteImport.update({
  id: '/elektrokola',
  path: '/elektrokola',
  getParentRoute: () => rootRouteImport,
} as any)
const KolaRoute = KolaRouteImport.update({
  id: '/kola',
  path: '/kola',
  getParentRoute: () => rootRouteImport,
} as any)
const KontaktRoute = KontaktRouteImport.update({
  id: '/kontakt',
  path: '/kontakt',
  getParentRoute: () => rootRouteImport,
} as any)
const KosikRoute = KosikRouteImport.update({
  id: '/kosik',
  path: '/kosik',
  getParentRoute: () => rootRouteImport,
} as any)
const OMneRoute = OMneRouteImport.update({
  id: '/o-mne',
  path: '/o-mne',
  getParentRoute: () => rootRouteImport,
} as any)
const ObchodniPodminkyRoute = ObchodniPodminkyRouteImport.update({
  id: '/obchodni-podminky',
  path: '/obchodni-podminky',
  getParentRoute: () => rootRouteImport,
} as any)
const OchranaOsobnichUdajuRoute = OchranaOsobnichUdajuRouteImport.update({
  id: '/ochrana-osobnich-udaju',
  path: '/ochrana-osobnich-udaju',
  getParentRoute: () => rootRouteImport,
} as any)
const OdstoupeniOdSmlouvyRoute = OdstoupeniOdSmlouvyRouteImport.update({
  id: '/odstoupeni-od-smlouvy',
  path: '/odstoupeni-od-smlouvy',
  getParentRoute: () => rootRouteImport,
} as any)
const ServisRoute = ServisRouteImport.update({
  id: '/servis',
  path: '/servis',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ElektrokolaIndexRoute = ElektrokolaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ElektrokolaRoute,
} as any)
const ElektrokolaZnackaRoute = ElektrokolaZnackaRouteImport.update({
  id: '/$znacka',
  path: '/$znacka',
  getParentRoute: () => ElektrokolaRoute,
} as any)
const KolaIndexRoute = KolaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => KolaRoute,
} as any)
const KolaZnackaRoute = KolaZnackaRouteImport.update({
  id: '/$znacka',
  path: '/$znacka',
  getParentRoute: () => KolaRoute,
} as any)
const KoloSlugRoute = KoloSlugRouteImport.update({
  id: '/kolo/$slug',
  path: '/kolo/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminKategorieRoute =
  AuthenticatedAdminKategorieRouteImport.update({
    id: '/kategorie',
    path: '/kategorie',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminNastaveniRoute =
  AuthenticatedAdminNastaveniRouteImport.update({
    id: '/nastaveni',
    path: '/nastaveni',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminObjednavkyRoute =
  AuthenticatedAdminObjednavkyRouteImport.update({
    id: '/objednavky',
    path: '/objednavky',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminProduktyRoute =
  AuthenticatedAdminProduktyRouteImport.update({
    id: '/produkty',
    path: '/produkty',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminServisRoute =
  AuthenticatedAdminServisRouteImport.update({
    id: '/servis',
    path: '/servis',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSpravciRoute =
  AuthenticatedAdminSpravciRouteImport.update({
    id: '/spravci',
    path: '/spravci',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminZpravyRoute =
  AuthenticatedAdminZpravyRouteImport.update({
    id: '/zpravy',
    path: '/zpravy',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/bazar': typeof BazarRoute
  '/elektrokola': typeof ElektrokolaRouteWithChildren
  '/kola': typeof KolaRouteWithChildren
  '/kontakt': typeof KontaktRoute
  '/kosik': typeof KosikRoute
  '/o-mne': typeof OMneRoute
  '/obchodni-podminky': typeof ObchodniPodminkyRoute
  '/ochrana-osobnich-udaju': typeof OchranaOsobnichUdajuRoute
  '/odstoupeni-od-smlouvy': typeof OdstoupeniOdSmlouvyRoute
  '/servis': typeof ServisRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/elektrokola/$znacka': typeof ElektrokolaZnackaRoute
  '/kola/$znacka': typeof KolaZnackaRoute
  '/kolo/$slug': typeof KoloSlugRoute
  '/elektrokola/': typeof ElektrokolaIndexRoute
  '/kola/': typeof KolaIndexRoute
  '/admin/kategorie': typeof AuthenticatedAdminKategorieRoute
  '/admin/nastaveni': typeof AuthenticatedAdminNastaveniRoute
  '/admin/objednavky': typeof AuthenticatedAdminObjednavkyRoute
  '/admin/produkty': typeof AuthenticatedAdminProduktyRoute
  '/admin/servis': typeof AuthenticatedAdminServisRoute
  '/admin/spravci': typeof AuthenticatedAdminSpravciRoute
  '/admin/zpravy': typeof AuthenticatedAdminZpravyRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/bazar': typeof BazarRoute
  '/kontakt': typeof KontaktRoute
  '/kosik': typeof KosikRoute
  '/o-mne': typeof OMneRoute
  '/obchodni-podminky': typeof ObchodniPodminkyRoute
  '/ochrana-osobnich-udaju': typeof OchranaOsobnichUdajuRoute
  '/odstoupeni-od-smlouvy': typeof OdstoupeniOdSmlouvyRoute
  '/servis': typeof ServisRoute
  '/elektrokola/$znacka': typeof ElektrokolaZnackaRoute
  '/kola/$znacka': typeof KolaZnackaRoute
  '/kolo/$slug': typeof KoloSlugRoute
  '/elektrokola': typeof ElektrokolaIndexRoute
  '/kola': typeof KolaIndexRoute
  '/admin/kategorie': typeof AuthenticatedAdminKategorieRoute
  '/admin/nastaveni': typeof AuthenticatedAdminNastaveniRoute
  '/admin/objednavky': typeof AuthenticatedAdminObjednavkyRoute
  '/admin/produkty': typeof AuthenticatedAdminProduktyRoute
  '/admin/servis': typeof AuthenticatedAdminServisRoute
  '/admin/spravci': typeof AuthenticatedAdminSpravciRoute
  '/admin/zpravy': typeof AuthenticatedAdminZpravyRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/bazar': typeof BazarRoute
  '/elektrokola': typeof ElektrokolaRouteWithChildren
  '/kola': typeof KolaRouteWithChildren
  '/kontakt': typeof KontaktRoute
  '/kosik': typeof KosikRoute
  '/o-mne': typeof OMneRoute
  '/obchodni-podminky': typeof ObchodniPodminkyRoute
  '/ochrana-osobnich-udaju': typeof OchranaOsobnichUdajuRoute
  '/odstoupeni-od-smlouvy': typeof OdstoupeniOdSmlouvyRoute
  '/servis': typeof ServisRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/elektrokola/$znacka': typeof ElektrokolaZnackaRoute
  '/kola/$znacka': typeof KolaZnackaRoute
  '/kolo/$slug': typeof KoloSlugRoute
  '/elektrokola/': typeof ElektrokolaIndexRoute
  '/kola/': typeof KolaIndexRoute
  '/_authenticated/admin/kategorie': typeof AuthenticatedAdminKategorieRoute
  '/_authenticated/admin/nastaveni': typeof AuthenticatedAdminNastaveniRoute
  '/_authenticated/admin/objednavky': typeof AuthenticatedAdminObjednavkyRoute
  '/_authenticated/admin/produkty': typeof AuthenticatedAdminProduktyRoute
  '/_authenticated/admin/servis': typeof AuthenticatedAdminServisRoute
  '/_authenticated/admin/spravci': typeof AuthenticatedAdminSpravciRoute
  '/_authenticated/admin/zpravy': typeof AuthenticatedAdminZpravyRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/bazar'
    | '/elektrokola'
    | '/kola'
    | '/kontakt'
    | '/kosik'
    | '/o-mne'
    | '/obchodni-podminky'
    | '/ochrana-osobnich-udaju'
    | '/odstoupeni-od-smlouvy'
    | '/servis'
    | '/admin'
    | '/elektrokola/$znacka'
    | '/kola/$znacka'
    | '/kolo/$slug'
    | '/elektrokola/'
    | '/kola/'
    | '/admin/kategorie'
    | '/admin/nastaveni'
    | '/admin/objednavky'
    | '/admin/produkty'
    | '/admin/servis'
    | '/admin/spravci'
    | '/admin/zpravy'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/bazar'
    | '/kontakt'
    | '/kosik'
    | '/o-mne'
    | '/obchodni-podminky'
    | '/ochrana-osobnich-udaju'
    | '/odstoupeni-od-smlouvy'
    | '/servis'
    | '/elektrokola/$znacka'
    | '/kola/$znacka'
    | '/kolo/$slug'
    | '/elektrokola'
    | '/kola'
    | '/admin/kategorie'
    | '/admin/nastaveni'
    | '/admin/objednavky'
    | '/admin/produkty'
    | '/admin/servis'
    | '/admin/spravci'
    | '/admin/zpravy'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/bazar'
    | '/elektrokola'
    | '/kola'
    | '/kontakt'
    | '/kosik'
    | '/o-mne'
    | '/obchodni-podminky'
    | '/ochrana-osobnich-udaju'
    | '/odstoupeni-od-smlouvy'
    | '/servis'
    | '/_authenticated/admin'
    | '/elektrokola/$znacka'
    | '/kola/$znacka'
    | '/kolo/$slug'
    | '/elektrokola/'
    | '/kola/'
    | '/_authenticated/admin/kategorie'
    | '/_authenticated/admin/nastaveni'
    | '/_authenticated/admin/objednavky'
    | '/_authenticated/admin/produkty'
    | '/_authenticated/admin/servis'
    | '/_authenticated/admin/spravci'
    | '/_authenticated/admin/zpravy'
    | '/_authenticated/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  BazarRoute: typeof BazarRoute
  ElektrokolaRoute: typeof ElektrokolaRouteWithChildren
  KolaRoute: typeof KolaRouteWithChildren
  KontaktRoute: typeof KontaktRoute
  KosikRoute: typeof KosikRoute
  OMneRoute: typeof OMneRoute
  ObchodniPodminkyRoute: typeof ObchodniPodminkyRoute
  OchranaOsobnichUdajuRoute: typeof OchranaOsobnichUdajuRoute
  OdstoupeniOdSmlouvyRoute: typeof OdstoupeniOdSmlouvyRoute
  ServisRoute: typeof ServisRoute
  KoloSlugRoute: typeof KoloSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bazar': {
      id: '/bazar'
      path: '/bazar'
      fullPath: '/bazar'
      preLoaderRoute: typeof BazarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/elektrokola': {
      id: '/elektrokola'
      path: '/elektrokola'
      fullPath: '/elektrokola'
      preLoaderRoute: typeof ElektrokolaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kola': {
      id: '/kola'
      path: '/kola'
      fullPath: '/kola'
      preLoaderRoute: typeof KolaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontakt': {
      id: '/kontakt'
      path: '/kontakt'
      fullPath: '/kontakt'
      preLoaderRoute: typeof KontaktRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kosik': {
      id: '/kosik'
      path: '/kosik'
      fullPath: '/kosik'
      preLoaderRoute: typeof KosikRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/o-mne': {
      id: '/o-mne'
      path: '/o-mne'
      fullPath: '/o-mne'
      preLoaderRoute: typeof OMneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/obchodni-podminky': {
      id: '/obchodni-podminky'
      path: '/obchodni-podminky'
      fullPath: '/obchodni-podminky'
      preLoaderRoute: typeof ObchodniPodminkyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ochrana-osobnich-udaju': {
      id: '/ochrana-osobnich-udaju'
      path: '/ochrana-osobnich-udaju'
      fullPath: '/ochrana-osobnich-udaju'
      preLoaderRoute: typeof OchranaOsobnichUdajuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/odstoupeni-od-smlouvy': {
      id: '/odstoupeni-od-smlouvy'
      path: '/odstoupeni-od-smlouvy'
      fullPath: '/odstoupeni-od-smlouvy'
      preLoaderRoute: typeof OdstoupeniOdSmlouvyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servis': {
      id: '/servis'
      path: '/servis'
      fullPath: '/servis'
      preLoaderRoute: typeof ServisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/elektrokola/': {
      id: '/elektrokola/'
      path: '/'
      fullPath: '/elektrokola/'
      preLoaderRoute: typeof ElektrokolaIndexRouteImport
      parentRoute: typeof ElektrokolaRoute
    }
    '/elektrokola/$znacka': {
      id: '/elektrokola/$znacka'
      path: '/$znacka'
      fullPath: '/elektrokola/$znacka'
      preLoaderRoute: typeof ElektrokolaZnackaRouteImport
      parentRoute: typeof ElektrokolaRoute
    }
    '/kola/': {
      id: '/kola/'
      path: '/'
      fullPath: '/kola/'
      preLoaderRoute: typeof KolaIndexRouteImport
      parentRoute: typeof KolaRoute
    }
    '/kola/$znacka': {
      id: '/kola/$znacka'
      path: '/$znacka'
      fullPath: '/kola/$znacka'
      preLoaderRoute: typeof KolaZnackaRouteImport
      parentRoute: typeof KolaRoute
    }
    '/kolo/$slug': {
      id: '/kolo/$slug'
      path: '/kolo/$slug'
      fullPath: '/kolo/$slug'
      preLoaderRoute: typeof KoloSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/kategorie': {
      id: '/_authenticated/admin/kategorie'
      path: '/kategorie'
      fullPath: '/admin/kategorie'
      preLoaderRoute: typeof AuthenticatedAdminKategorieRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/nastaveni': {
      id: '/_authenticated/admin/nastaveni'
      path: '/nastaveni'
      fullPath: '/admin/nastaveni'
      preLoaderRoute: typeof AuthenticatedAdminNastaveniRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/objednavky': {
      id: '/_authenticated/admin/objednavky'
      path: '/objednavky'
      fullPath: '/admin/objednavky'
      preLoaderRoute: typeof AuthenticatedAdminObjednavkyRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/produkty': {
      id: '/_authenticated/admin/produkty'
      path: '/produkty'
      fullPath: '/admin/produkty'
      preLoaderRoute: typeof AuthenticatedAdminProduktyRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/servis': {
      id: '/_authenticated/admin/servis'
      path: '/servis'
      fullPath: '/admin/servis'
      preLoaderRoute: typeof AuthenticatedAdminServisRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/spravci': {
      id: '/_authenticated/admin/spravci'
      path: '/spravci'
      fullPath: '/admin/spravci'
      preLoaderRoute: typeof AuthenticatedAdminSpravciRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/zpravy': {
      id: '/_authenticated/admin/zpravy'
      path: '/zpravy'
      fullPath: '/admin/zpravy'
      preLoaderRoute: typeof AuthenticatedAdminZpravyRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminKategorieRoute: typeof AuthenticatedAdminKategorieRoute
  AuthenticatedAdminNastaveniRoute: typeof AuthenticatedAdminNastaveniRoute
  AuthenticatedAdminObjednavkyRoute: typeof AuthenticatedAdminObjednavkyRoute
  AuthenticatedAdminProduktyRoute: typeof AuthenticatedAdminProduktyRoute
  AuthenticatedAdminServisRoute: typeof AuthenticatedAdminServisRoute
  AuthenticatedAdminSpravciRoute: typeof AuthenticatedAdminSpravciRoute
  AuthenticatedAdminZpravyRoute: typeof AuthenticatedAdminZpravyRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminKategorieRoute: AuthenticatedAdminKategorieRoute,
  AuthenticatedAdminNastaveniRoute: AuthenticatedAdminNastaveniRoute,
  AuthenticatedAdminObjednavkyRoute: AuthenticatedAdminObjednavkyRoute,
  AuthenticatedAdminProduktyRoute: AuthenticatedAdminProduktyRoute,
  AuthenticatedAdminServisRoute: AuthenticatedAdminServisRoute,
  AuthenticatedAdminSpravciRoute: AuthenticatedAdminSpravciRoute,
  AuthenticatedAdminZpravyRoute: AuthenticatedAdminZpravyRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface ElektrokolaRouteChildren {
  ElektrokolaZnackaRoute: typeof ElektrokolaZnackaRoute
  ElektrokolaIndexRoute: typeof ElektrokolaIndexRoute
}

const ElektrokolaRouteChildren: ElektrokolaRouteChildren = {
  ElektrokolaZnackaRoute: ElektrokolaZnackaRoute,
  ElektrokolaIndexRoute: ElektrokolaIndexRoute,
}

const ElektrokolaRouteWithChildren = ElektrokolaRoute._addFileChildren(
  ElektrokolaRouteChildren,
)

interface KolaRouteChildren {
  KolaZnackaRoute: typeof KolaZnackaRoute
  KolaIndexRoute: typeof KolaIndexRoute
}

const KolaRouteChildren: KolaRouteChildren = {
  KolaZnackaRoute: KolaZnackaRoute,
  KolaIndexRoute: KolaIndexRoute,
}

const KolaRouteWithChildren = KolaRoute._addFileChildren(KolaRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  BazarRoute: BazarRoute,
  ElektrokolaRoute: ElektrokolaRouteWithChildren,
  KolaRoute: KolaRouteWithChildren,
  KontaktRoute: KontaktRoute,
  KosikRoute: KosikRoute,
  OMneRoute: OMneRoute,
  ObchodniPodminkyRoute: ObchodniPodminkyRoute,
  OchranaOsobnichUdajuRoute: OchranaOsobnichUdajuRoute,
  OdstoupeniOdSmlouvyRoute: OdstoupeniOdSmlouvyRoute,
  ServisRoute: ServisRoute,
  KoloSlugRoute: KoloSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
